<?php

namespace Application\Modules\Frontend\Controllers;

class IndexController extends ControllerBase
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {

    }

}

