<?php
namespace Application\Modules\Backend\Controllers;
class DashboardController extends ControllerBase
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index1Action()
    {

    }

}

