<?php

namespace Application\Modules\Backend\Controllers;

use Application\Common\Models\PermissionRole;

class IndexController extends ControllerBase
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        $menus = (new PermissionRole())->getMenus($this->session->get('auth')['roles_id']);
        $this->view->setVar('menus',$menus);
    }


    public function show404Action(){
        if($this->request->isAjax()){

        }
        return "404 NOT FOUND";
    }
}

