<?php

namespace Application\Modules\Api\Controllers;

use Application\Common\Models\Admins;
use Application\Common\Models\RoleAdmin;

class AuthController extends ControllerBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

    }

    public function startAction(){
        if($this->request->isPost()){
            $email = $this->params['email'];
            $password = $this->params['password'];
            // search user from db
            $admin = Admins::findFirst(array(
                "email = :email:",
                'bind' => array(
                    'email'    => $email,
                )
            ));
            if(!$admin){
                return $this->response->setJsonContent(['data'=>$admin]);
            }
            if($this->security->checkHash($password, $admin->password)){
                $roles_info = (new RoleAdmin())->getRole($admin->id);
                $roles_info = array(pluck($roles_info,['name']),implode(',',pluck($roles_info,['id'])));
                return $this->response->setJsonContent(['data'=>$roles_info]);
            }else{
                return $this->response->setJsonContent(['data'=>false]);
            }
        }
    }

}

