<?php

namespace Application\Modules\Api\Controllers;

use Phalcon\Mvc\View;

class IndexController extends ControllerBase
{

    protected $ss;
    public function initialize()
    {

        parent::initialize(); // TODO: Change the autogenerated stub
        $this->view->setRenderLevel(View::LEVEL_NO_RENDER);

    }

    public function indexAction()
    {
        return $this->response->setJsonContent(['xxx']);
    }


    public function show404Action(){

    }

}

